version: "3.7"

services:
  myapitemplate:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mindee-fileupload
    restart: always
    env_file:
      - app/dev.env
    volumes:
      - "./app:/app"
    ports:
      - "8080:8080"
